services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: healing-hearts-minds-bot
    container_name: hhmBot
    hostname: hhmBot
    entrypoint: /usr/local/bin/entrypoint.sh
    env_file: ./.env
    tty: true
    volumes:
      - ./src:/code/src
