# fly.toml app configuration file generated for healing-hearts-minds-bot on 2024-08-10T15:17:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'healing-hearts-minds-bot'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
